### DISCUSSION TITLE
Mac clipboard - unexpected output?

### DISCUSSION THREAD

**Discussion by Pe8er** [manna-harbour/miryoku#186] [Q&A] [answered]
Hey everyone!

I set clipboard to "Mac" in my build workflow file like so:

```
name: 'Build Example corne nice_nano_v2 nice_view'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left nice_view_adapter nice_view","corne_right nice_view_adapter nice_view"]'
      clipboard: '["mac"]'
      kconfig: '["CONFIG_BT_CTLR_TX_PWR_PLUS_8=y\nCONFIG_ZMK_SLEEP=y\nCONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000\nCONFIG_ZMK_WIDGET_WPM_STATUS=n"]'
```

[build-example-corne-nice_nano_v2-nice_view.yml](https://github.com/Pe8er/miryoku_zmk/blob/5a19b57113d303fcf9496c5e66afe36f23761a59/.github/workflows/build-example-corne-nice_nano_v2-nice_view.yml#L13)

However, clipboard keys behave in a seemingly strange way. Here's what Karabiner-EventViewer reports:

* Paste: left_shift + insert
* Copy: left_control + insert
* Cut: left shift + delete_forward

Interestingly, it looks like build workflow doesn't pick up `clipboard: '["mac"]'` setting because I added a bunch of garbage to [miryoku_clipboard.h](https://github.com/Pe8er/miryoku_zmk/blob/5a19b57113d303fcf9496c5e66afe36f23761a59/miryoku/miryoku_clipboard.h#L13) and the build still went through.

What am I missing?
