### DISCUSSION TITLE
ZMK Mouse and Suspend fixes cannot be merged using Github Actions

### DISCUSSION THREAD

**Discussion by gogamid** [manna-harbour/miryoku#284] [Q&A] [answered]
I used this action:
```yml
name: "Run My Config"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left","corne_right"]'
      nav: '["invertedt"]'
      layers: '["flip"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR","#define MIRYOKU_KLUDGE_SUSPEND"]'
      branches: '["zmkfirmware/zmk/main caksoylar/zmk/feat/mouse-keys-3.2 manna-harbour/zmk/suspend-test"]'
```
tried also with:
`custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR\n#define MIRYOKU_KLUDGE_SUSPEND"]'`

Getting Merge Error:
<img width="941" alt="image" src="https://github.com/manna-harbour/miryoku/assets/36050790/7b8377e7-b4df-41bb-934e-fb14b2cce632">
